/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiugestionegite;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utente
 */
public class FrmCambiaClasse extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCambiaClasse.class.getName());
    private Classe classeDaEliminare; //classe da eliminare
    private DefaultTableModel tabellaStudenti; //riferimento alla tabella di studenti sul form principale
    private DefaultTableModel tabellaClassi; //riferimento alla tabella di classi sul form principale
    /**
     * Creates new form FrmCambiaClasse
     */
    public FrmCambiaClasse(Classe c, DefaultTableModel tabellaStudenti, DefaultTableModel tabellaClassi) {
        initComponents();
        classeDaEliminare = c;
        this.tabellaStudenti = tabellaStudenti;
        this.tabellaClassi = tabellaClassi;
        //configurazione componenti
        configuraComboBox();
        configuraTabella();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiaClasse = new javax.swing.JButton();
        srpStudenti = new javax.swing.JScrollPane();
        tblStudenti = new javax.swing.JTable();
        pnlIscriviStudente = new javax.swing.JPanel();
        lblIscriviStudente = new javax.swing.JLabel();
        cmbClasse = new javax.swing.JComboBox<>();
        lblClasse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assegnazione nuova classe");

        btnCambiaClasse.setText("Cambia classe");
        btnCambiaClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiaClasseActionPerformed(evt);
            }
        });

        tblStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricola", "Nome", "Cognome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srpStudenti.setViewportView(tblStudenti);

        pnlIscriviStudente.setBackground(new java.awt.Color(153, 204, 255));

        lblIscriviStudente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIscriviStudente.setText("Cambia classe");

        javax.swing.GroupLayout pnlIscriviStudenteLayout = new javax.swing.GroupLayout(pnlIscriviStudente);
        pnlIscriviStudente.setLayout(pnlIscriviStudenteLayout);
        pnlIscriviStudenteLayout.setHorizontalGroup(
            pnlIscriviStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIscriviStudenteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIscriviStudente)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        pnlIscriviStudenteLayout.setVerticalGroup(
            pnlIscriviStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIscriviStudenteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblIscriviStudente)
                .addGap(19, 19, 19))
        );

        lblClasse.setText("Classe nuova:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIscriviStudente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCambiaClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srpStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlIscriviStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(srpStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiaClasse)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiaClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiaClasseActionPerformed
        //controllo selezione
        if(getMatricolaStudenteSelezionato() == -1){
            JOptionPane.showMessageDialog(this, "Devi selezionare lo studente a cui vuoi assegnare questa classe", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //assegnazione nuova classe
        Classe c = (Classe)cmbClasse.getSelectedItem();
        Studente s = GestioneStudenti.cercaPerMatricola(getMatricolaStudenteSelezionato());
        s.setClasse(c);
        GestioneDatabase.aggiornaClasseStudente(s.getMatricola(), c.getId());
        System.out.println("Classe cambiata");
        //rimozione studente con nuova classe
        DefaultTableModel modello = (DefaultTableModel)tblStudenti.getModel();
        modello.removeRow(tblStudenti.getSelectedRow());
        //aggiornamento tabella studenti sul form principale
        aggiornaTabellaStudenti();
        //controllo per vedere se sono finiti gli studenti appartenenti alla classe da eliminare
        if(controlloFineAssegnazioneClassi()){
            //chiusura form
            this.dispose();
        }
    }//GEN-LAST:event_btnCambiaClasseActionPerformed

    /**
     * Restituisce l'ID (matricola) dello studente attualmente selezionato nella tabella
     * @return L'ID dello studente, oppure -1 se nessuna riga è selezionata.
     */
    private int getMatricolaStudenteSelezionato() {
        int rigaSelezionata = tblStudenti.getSelectedRow();
        if (rigaSelezionata != -1) {
            Integer matricola = (Integer)tblStudenti.getValueAt(rigaSelezionata, 0);
            return Integer.parseInt(matricola.toString());

        }
        return -1;
    }
    /**
     * Metodo per inserire btutte le classi sulla combobox
     */
    private void configuraComboBox(){
        //caricamento classi, escludendo quella da eliminare
        for (Classe c : GestioneDatabase.getListaClassi()) {
            if(!c.equals(classeDaEliminare)) cmbClasse.addItem(c);
        }
    }
    /**
     * Metodo per configurare la tabella
     */
    private void configuraTabella(){
        DefaultTableModel modello = (DefaultTableModel)tblStudenti.getModel();
        //caricamento studenti della classe da eliminare
        for(Studente s : GestioneStudenti.cercaStudentiPerClasse(classeDaEliminare)){
            modello.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome(), s.getClasse()});
        }
    }
    
    /**
     * Metodo per controllare se tutti gli studenti hanno una nuova classe
     * @return 
     */
    public boolean controlloFineAssegnazioneClassi(){
        if(GestioneStudenti.cercaStudentiPerClasse(classeDaEliminare).isEmpty()){
            //eliminazione classe
            GestioneDatabase.rimuoviClasse(classeDaEliminare.getId());
            GestioneClassi.rimuoviClasse(classeDaEliminare.getId());
            aggiornaTabellaClassi();
            JOptionPane.showMessageDialog(this, "Tutti gli studenti della classe " + classeDaEliminare + " hanno una nuova classe. \n la classe " + classeDaEliminare + " e' stata eliminata", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }
    
    /**
     * Metodo per aggiornare la tabella con le classi
     */
    public void aggiornaTabellaStudenti(){
        tabellaStudenti.setRowCount(0);
        for (Studente s : GestioneDatabase.getListaStudenti()) {
            tabellaStudenti.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome(), s.getClasse()});
        }

    }
    
    /**
     * Metodo per aggiornare la tabella con le classi
     */
    public void aggiornaTabellaClassi(){
        tabellaClassi.setRowCount(0);
        for (Classe c : GestioneDatabase.getListaClassi()) {
            tabellaClassi.addRow(new Object[]{c.getId(), c.getAnno(), c.getSezione(), c.getIndirizzo()});
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiaClasse;
    private javax.swing.JComboBox<Classe> cmbClasse;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblIscriviStudente;
    private javax.swing.JPanel pnlIscriviStudente;
    private javax.swing.JScrollPane srpStudenti;
    private javax.swing.JTable tblStudenti;
    // End of variables declaration//GEN-END:variables
}
