/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package aurelimartinellipichiugestionegite;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aureli.giulia
 */
public class FrmGestioneGite extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestioneGite.class.getName());

    /** Creates new form FrmPartecipazione */
    public FrmGestioneGite() {
        initComponents();
        //caricamento tabelle
        aggiornaTabellaClassi();
        aggiornaTabellaGite();
        aggiornaTabellaStudenti();
        //configurazione tabelle
        srpClassi.setVisible(false);
        srpGite.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitoloGestioneMagazzino = new javax.swing.JPanel();
        lblGestioneMagazzino = new javax.swing.JLabel();
        cmbTabelle = new javax.swing.JComboBox<>();
        srpStudenti = new javax.swing.JScrollPane();
        tblStudenti = new javax.swing.JTable();
        btnAggiungi = new javax.swing.JButton();
        btnIscrivi = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        srpClassi = new javax.swing.JScrollPane();
        tblClassi = new javax.swing.JTable();
        srpGite = new javax.swing.JScrollPane();
        tblGite = new javax.swing.JTable();
        btnVediIscrizioni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione gite");
        setMinimumSize(new java.awt.Dimension(620, 400));
        setPreferredSize(new java.awt.Dimension(610, 400));
        getContentPane().setLayout(null);

        pnlTitoloGestioneMagazzino.setBackground(new java.awt.Color(102, 102, 255));

        lblGestioneMagazzino.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblGestioneMagazzino.setForeground(new java.awt.Color(255, 255, 255));
        lblGestioneMagazzino.setText("Gestione Gite");

        javax.swing.GroupLayout pnlTitoloGestioneMagazzinoLayout = new javax.swing.GroupLayout(pnlTitoloGestioneMagazzino);
        pnlTitoloGestioneMagazzino.setLayout(pnlTitoloGestioneMagazzinoLayout);
        pnlTitoloGestioneMagazzinoLayout.setHorizontalGroup(
            pnlTitoloGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGestioneMagazzino)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        pnlTitoloGestioneMagazzinoLayout.setVerticalGroup(
            pnlTitoloGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblGestioneMagazzino)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTitoloGestioneMagazzino);
        pnlTitoloGestioneMagazzino.setBounds(0, 0, 603, 70);

        cmbTabelle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Studenti", "Classi", "Gite" }));
        cmbTabelle.addItemListener(this::cmbTabelleItemStateChanged);
        getContentPane().add(cmbTabelle);
        cmbTabelle.setBounds(20, 80, 180, 22);

        tblStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricola", "Nome", "Cognome", "Classe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srpStudenti.setViewportView(tblStudenti);

        getContentPane().add(srpStudenti);
        srpStudenti.setBounds(20, 110, 360, 241);

        btnAggiungi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(this::btnAggiungiActionPerformed);
        getContentPane().add(btnAggiungi);
        btnAggiungi.setBounds(400, 110, 185, 30);

        btnIscrivi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnIscrivi.setText("Iscrivi");
        btnIscrivi.addActionListener(this::btnIscriviActionPerformed);
        getContentPane().add(btnIscrivi);
        btnIscrivi.setBounds(400, 170, 185, 35);

        btnElimina.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnElimina.setText("Elimina");
        btnElimina.addActionListener(this::btnEliminaActionPerformed);
        getContentPane().add(btnElimina);
        btnElimina.setBounds(400, 310, 185, 35);

        tblClassi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Anno", "Sezione", "Indirizzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srpClassi.setViewportView(tblClassi);

        getContentPane().add(srpClassi);
        srpClassi.setBounds(20, 110, 360, 241);

        tblGite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Destinazione", "Durata", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srpGite.setViewportView(tblGite);

        getContentPane().add(srpGite);
        srpGite.setBounds(20, 110, 360, 241);

        btnVediIscrizioni.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVediIscrizioni.setText("Vedi iscrizioni");
        btnVediIscrizioni.addActionListener(this::btnVediIscrizioniActionPerformed);
        getContentPane().add(btnVediIscrizioni);
        btnVediIscrizioni.setBounds(400, 240, 185, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        String tabellaSelezionata = cmbTabelle.getSelectedItem().toString();
        if (tabellaSelezionata.equals("Studenti")) {
            //controllo per vedere se e' presente almeno una classe
            if(GestioneClassi.getListaClassi().size() == 0){
                JOptionPane.showMessageDialog(this, "Devi creare una classe prima di creare uno studente", "Attenzione", JOptionPane.WARNING_MESSAGE);
                return;
            }
            DefaultTableModel model = (DefaultTableModel)tblStudenti.getModel();
            // Apre il form per aggiungere uno studente
            FrmStudente frmStudente = new FrmStudente(model);
            frmStudente.setVisible(true);
            
        } else if (tabellaSelezionata.equals("Classi")) {
            DefaultTableModel model = (DefaultTableModel)tblClassi.getModel();
            // Apre il form per aggiungere una classe
            FrmClasse frmClasse = new FrmClasse(model);
            frmClasse.setVisible(true);
            
        } else if (tabellaSelezionata.equals("Gite")) {
            DefaultTableModel model = (DefaultTableModel)tblGite.getModel();
            // Apre il form per aggiungere una gita
            FrmGita frmGita = new FrmGita(model);
            frmGita.setVisible(true);
        }
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void cmbTabelleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTabelleItemStateChanged
        String oggettoSelezionato = cmbTabelle.getSelectedItem().toString();
        srpGite.setVisible(false);
        srpClassi.setVisible(false);
        srpStudenti.setVisible(false);
        //rende visibile la tabella che si vuole vedere
        if (oggettoSelezionato.equals("Studenti")) {
            srpStudenti.setVisible(true);
        } else if (oggettoSelezionato.equals("Classi")) {
           srpClassi.setVisible(true);
        } else if (oggettoSelezionato.equals("Gite")) {
           srpGite.setVisible(true);
        }
    }//GEN-LAST:event_cmbTabelleItemStateChanged

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        String tabellaSelezionata = cmbTabelle.getSelectedItem().toString();
        //controllo per vedere cosa si vuole eliminare
        if (tabellaSelezionata.equals("Studenti")) {
            eliminazioneStudente();
        } else if (tabellaSelezionata.equals("Classi")) {
            eliminazioneClasse();
        } else if (tabellaSelezionata.equals("Gite")) {
            eliminazioneGita();
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnIscriviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscriviActionPerformed
        int matricola = getMatricolaStudenteSelezionato();
        Studente s = GestioneStudenti.cercaPerMatricola(matricola);
        //cotrollo selezione studente
        if(matricola == -1){
            JOptionPane.showMessageDialog(this, "Devi selezionare uno studente da iscrivere", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //controllo per vedere se lo studente e' gia' iscritto a tutte le gite
        else if(controlloIscrizioni(s)){
            JOptionPane.showMessageDialog(this, "Questo studente e' gia' iscritto a tutte le gite create", "errore", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //apertura form per iscrizione alle gite
        FrmIscriviStudente frmIscriviStudente = new FrmIscriviStudente(s);
        frmIscriviStudente.setVisible(true);
    }//GEN-LAST:event_btnIscriviActionPerformed

    private void btnVediIscrizioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVediIscrizioniActionPerformed
        //controllo selezione studente
        if(tblStudenti.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Seleziona lo studente di cui vuoi vedere le iscrizioni", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //apertura form per vedere le iscrizioni di uno studente
        FrmVediIscrizioni frmVediIscrizioni = new FrmVediIscrizioni(GestioneStudenti.cercaPerMatricola(getMatricolaStudenteSelezionato()));
        frmVediIscrizioni.setVisible(true);
    }//GEN-LAST:event_btnVediIscrizioniActionPerformed

    /**
     * Metodo per controllare se uno studente e' iscritto a tutte le gite
     * @param s studente
     * @return true se e' iscritto a tutte le gite, false altrimenti
     */
    private boolean controlloIscrizioni(Studente s){
        for(Gita g : GestioneGite.getListaGite()){
            if(!s.getIdGita().contains(g.getId())) return false;
        }
        return true;
    }
    /**
     * Metodo per aggiornare la tabella con le classi
     */
    public void aggiornaTabellaClassi(){
        DefaultTableModel model = (DefaultTableModel)tblClassi.getModel();
        model.setRowCount(0);
        for (Classe c : GestioneDatabase.getListaClassi()) {
            model.addRow(new Object[]{c.getId(), c.getAnno(), c.getSezione(), c.getIndirizzo()});
        }

    }
    
    /**
     * Metodo per aggiornare la tabella con le classi
     */
    public void aggiornaTabellaGite(){
        DefaultTableModel model = (DefaultTableModel)tblGite.getModel();
        model.setRowCount(0);
        for (Gita g : GestioneDatabase.getListaGite()) {
            model.addRow(new Object[]{g.getId(), g.getDestinazione(), g.getDurata(), g.getPrezzo()});
        }

    }
    
    /**
     * Metodo per aggiornare la tabella con le classi
     */
    public void aggiornaTabellaStudenti(){
        DefaultTableModel model = (DefaultTableModel)tblStudenti.getModel();
        model.setRowCount(0);
        for (Studente s : GestioneDatabase.getListaStudenti()) {
            model.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome(), s.getClasse()});
        }

    }
    
    /**
     * Restituisce l'ID (matricola) dello studente attualmente selezionato nella
     * tabella.
     *
     * @return L'ID dello studente, oppure -1 se nessuna riga è selezionata.
     */
    private int getMatricolaStudenteSelezionato() {
        int rigaSelezionata = tblStudenti.getSelectedRow();
        if (rigaSelezionata != -1) {
            Integer matricola = (Integer)tblStudenti.getValueAt(rigaSelezionata, 0);
            return Integer.parseInt(matricola.toString());

        }
        return -1;
    }

    /**
     * Metodo per eliminare una classe
     */
    public void eliminazioneClasse() {
        //controllo selezione classe
        if(tblClassi.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Seleziona la classe che vuoi eliminare", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //controllo per vedere se e' rimasta solo una classe
        else if (GestioneClassi.getListaClassi().size() == 1) {
            JOptionPane.showMessageDialog(this, "Non puoi eliminare tutte le classi", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = (Integer) tblClassi.getValueAt(tblClassi.getSelectedRow(), 0);
        Classe c = GestioneClassi.cercaClassePerId(id);
        DefaultTableModel modello = (DefaultTableModel) tblClassi.getModel();
        //controllo per vedere se ci sono studenti appartenenti alla classe selezionata
        if (GestioneStudenti.cercaStudentiPerClasse(c).isEmpty()) {
            //eliminazione classe
            GestioneClassi.rimuoviClasse(id);
            GestioneDatabase.rimuoviClasse(id);
            modello.removeRow(tblClassi.getSelectedRow());
        } else {
            //apertura form per riassegnare la classe
            JOptionPane.showMessageDialog(this, "Prima di eliminare il " + c + " devi riassegnare le classi agli studenti di questa classe", "Attenzione", JOptionPane.WARNING_MESSAGE);
            FrmCambiaClasse frmCambiaClasse = new FrmCambiaClasse(c, (DefaultTableModel) tblStudenti.getModel(), modello);
            frmCambiaClasse.setVisible(true);
        }
    }
    
    /**
     * Metodo per eliminare uno studente
     */
    public void eliminazioneStudente(){
        //controllo selezione studente
        if(tblStudenti.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Seleziona lo studente che vuoi eliminare", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //eliminazione studente
        int matricola = getMatricolaStudenteSelezionato();
        DefaultTableModel modello = (DefaultTableModel)tblStudenti.getModel();
        modello.removeRow(tblStudenti.getSelectedRow());
        GestioneStudenti.rimuoviStudente(matricola);
        GestioneDatabase.rimuoviPartecipazioniPerStudente(matricola);
        GestioneDatabase.rimuoviStudente(matricola);
    }
    
    /**
     * Metodo per eliminare una gita
     */
    public void eliminazioneGita(){
        //conrollo selezione gita
        int rigaSelezionata = tblGite.getSelectedRow();
        if(rigaSelezionata == -1){
            JOptionPane.showMessageDialog(this, "Seleziona la gita che vuoi eliminare", "Attenzione", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //eliminazione gita
        int id = (Integer)tblGite.getValueAt(rigaSelezionata, 0);
        DefaultTableModel modello = (DefaultTableModel)tblGite.getModel();
        modello.removeRow(tblGite.getSelectedRow());
        GestioneGite.rimuoviGita(id);
        GestioneDatabase.rimuoviPartecipazioniPerGita(id);
        GestioneDatabase.rimuoviGita(id);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestioneGite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnIscrivi;
    private javax.swing.JButton btnVediIscrizioni;
    private javax.swing.JComboBox<String> cmbTabelle;
    private javax.swing.JLabel lblGestioneMagazzino;
    private javax.swing.JPanel pnlTitoloGestioneMagazzino;
    private javax.swing.JScrollPane srpClassi;
    private javax.swing.JScrollPane srpGite;
    private javax.swing.JScrollPane srpStudenti;
    private javax.swing.JTable tblClassi;
    private javax.swing.JTable tblGite;
    private javax.swing.JTable tblStudenti;
    // End of variables declaration//GEN-END:variables

}
