/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiugestionegite;

/**
 *
 * @author martinelli.alessandr
 */
public class FrmIscriviStudente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIscriviStudente.class.getName());
    private Studente s;
    /**
     * Creates new form FrmIscriviStudente
     */
    public FrmIscriviStudente(Studente s) {
        initComponents();
        this.s = s;
        configuraComboBox();
        configuraLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSfondo = new javax.swing.JPanel();
        pnlIscriviStudente = new javax.swing.JPanel();
        lblIscriviStudente = new javax.swing.JLabel();
        lblPerNome = new javax.swing.JLabel();
        lblPerCognome = new javax.swing.JLabel();
        lblPerClasse = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        lblGita = new javax.swing.JLabel();
        btnIscrivi = new javax.swing.JButton();
        cmbGite = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iscrizione studente");

        pnlIscriviStudente.setBackground(new java.awt.Color(153, 204, 255));

        lblIscriviStudente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIscriviStudente.setText("Iscrivi Studente");

        javax.swing.GroupLayout pnlIscriviStudenteLayout = new javax.swing.GroupLayout(pnlIscriviStudente);
        pnlIscriviStudente.setLayout(pnlIscriviStudenteLayout);
        pnlIscriviStudenteLayout.setHorizontalGroup(
            pnlIscriviStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIscriviStudenteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIscriviStudente)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        pnlIscriviStudenteLayout.setVerticalGroup(
            pnlIscriviStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIscriviStudenteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblIscriviStudente)
                .addGap(19, 19, 19))
        );

        lblPerNome.setText("Nome:");

        lblPerCognome.setText("Cognome:");

        lblPerClasse.setText("Classe:");

        lblGita.setText("Gita");

        btnIscrivi.setText("Iscrivi");
        btnIscrivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIscriviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSfondoLayout = new javax.swing.GroupLayout(pnlSfondo);
        pnlSfondo.setLayout(pnlSfondoLayout);
        pnlSfondoLayout.setHorizontalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIscriviStudente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSfondoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSfondoLayout.createSequentialGroup()
                        .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSfondoLayout.createSequentialGroup()
                                .addComponent(lblPerCognome)
                                .addGap(18, 18, 18)
                                .addComponent(lblCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSfondoLayout.createSequentialGroup()
                                .addComponent(lblPerNome)
                                .addGap(18, 18, 18)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addGroup(pnlSfondoLayout.createSequentialGroup()
                        .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerClasse)
                            .addGroup(pnlSfondoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblGita)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSfondoLayout.createSequentialGroup()
                                .addComponent(cmbGite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSfondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIscrivi)
                .addGap(16, 16, 16))
        );
        pnlSfondoLayout.setVerticalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSfondoLayout.createSequentialGroup()
                .addComponent(pnlIscriviStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPerNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerCognome)
                    .addComponent(lblCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerClasse)
                    .addComponent(lblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGita)
                    .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIscrivi)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSfondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIscriviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscriviActionPerformed
        Gita g = (Gita)cmbGite.getSelectedItem();
        s.iscrivi(g);
        GestioneDatabase.inserisciPartecipazione(s.getMatricola(), g.getId());
    }//GEN-LAST:event_btnIscriviActionPerformed

    /**
     * Metodo per inserire tutte le gite sulla combobox
     */
    private void configuraComboBox(){
        for (Gita g : GestioneGite.getListaGite()) {
            if(!s.controlloIdGita(g.getId())) cmbGite.addItem(g);
        }
    }
    
    private void configuraLabel(){
        lblNome.setText(s.getNome());
        lblCognome.setText(s.getCognome());
        lblClasse.setText(s.getClasse().toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIscrivi;
    private javax.swing.JComboBox<Gita> cmbGite;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblGita;
    private javax.swing.JLabel lblIscriviStudente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPerClasse;
    private javax.swing.JLabel lblPerCognome;
    private javax.swing.JLabel lblPerNome;
    private javax.swing.JPanel pnlIscriviStudente;
    private javax.swing.JPanel pnlSfondo;
    // End of variables declaration//GEN-END:variables
}
