/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package aurelimartinellipichiugestionegite;

/**
 *
 * @author aureli.giulia
 */
public class FrmPartecipazione extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPartecipazione.class.getName());

    /** Creates new form FrmPartecipazione */
    public FrmPartecipazione() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitoloGestioneMagazzino = new javax.swing.JPanel();
        lblGestioneMagazzino = new javax.swing.JLabel();
        btnNuovoProdotto = new javax.swing.JButton();
        pnlGestioneMagazzino = new javax.swing.JPanel();
        btnVendi = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnRifornisci = new javax.swing.JButton();
        btnStatistiche = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableStudenti1 = new javax.swing.JTable();
        cmbStudente = new javax.swing.JComboBox<>();
        btnElimina2 = new javax.swing.JButton();
        cmbGita = new javax.swing.JComboBox<>();
        btnLega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitoloGestioneMagazzino.setBackground(new java.awt.Color(102, 102, 255));

        lblGestioneMagazzino.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lblGestioneMagazzino.setForeground(new java.awt.Color(255, 255, 255));
        lblGestioneMagazzino.setText("Gestione Gite");

        btnNuovoProdotto.setBackground(new java.awt.Color(160, 160, 255));
        btnNuovoProdotto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnNuovoProdotto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuovoProdotto.setText("+  BOTTONE");
        btnNuovoProdotto.addActionListener(this::btnNuovoProdottoActionPerformed);

        javax.swing.GroupLayout pnlTitoloGestioneMagazzinoLayout = new javax.swing.GroupLayout(pnlTitoloGestioneMagazzino);
        pnlTitoloGestioneMagazzino.setLayout(pnlTitoloGestioneMagazzinoLayout);
        pnlTitoloGestioneMagazzinoLayout.setHorizontalGroup(
            pnlTitoloGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGestioneMagazzino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(btnNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlTitoloGestioneMagazzinoLayout.setVerticalGroup(
            pnlTitoloGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlTitoloGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuovoProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGestioneMagazzino))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlGestioneMagazzino.setBackground(new java.awt.Color(255, 255, 255));

        btnVendi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVendi.setText("BOTTONE");
        btnVendi.addActionListener(this::btnVendiActionPerformed);

        btnElimina.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnElimina.setText("BOT");
        btnElimina.addActionListener(this::btnEliminaActionPerformed);

        btnRifornisci.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnRifornisci.setText("BOTTONE");
        btnRifornisci.addActionListener(this::btnRifornisciActionPerformed);

        btnStatistiche.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnStatistiche.setText("BOT");
        btnStatistiche.addActionListener(this::btnStatisticheActionPerformed);

        tableStudenti1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Studente", "Classe", "Gita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableStudenti1);

        cmbStudente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnElimina2.setText("Elimina");

        cmbGita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLega.setText("Lega");

        javax.swing.GroupLayout pnlGestioneMagazzinoLayout = new javax.swing.GroupLayout(pnlGestioneMagazzino);
        pnlGestioneMagazzino.setLayout(pnlGestioneMagazzinoLayout);
        pnlGestioneMagazzinoLayout.setHorizontalGroup(
            pnlGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlGestioneMagazzinoLayout.createSequentialGroup()
                        .addComponent(cmbStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLega, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElimina2))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRifornisci)
                    .addComponent(btnVendi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistiche, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGestioneMagazzinoLayout.setVerticalGroup(
            pnlGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestioneMagazzinoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btnRifornisci)
                .addGap(39, 39, 39)
                .addComponent(btnVendi)
                .addGap(39, 39, 39)
                .addComponent(btnElimina)
                .addGap(39, 39, 39)
                .addComponent(btnStatistiche)
                .addGap(51, 51, 51))
            .addGroup(pnlGestioneMagazzinoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlGestioneMagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStudente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElimina2)
                    .addComponent(cmbGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLega))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitoloGestioneMagazzino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlGestioneMagazzino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitoloGestioneMagazzino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlGestioneMagazzino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuovoProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuovoProdottoActionPerformed
    }//GEN-LAST:event_btnNuovoProdottoActionPerformed

    private void btnVendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendiActionPerformed

    }//GEN-LAST:event_btnVendiActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed

    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnRifornisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRifornisciActionPerformed

    }//GEN-LAST:event_btnRifornisciActionPerformed

    private void btnStatisticheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticheActionPerformed

    }//GEN-LAST:event_btnStatisticheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPartecipazione().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnElimina2;
    private javax.swing.JButton btnLega;
    private javax.swing.JButton btnNuovoProdotto;
    private javax.swing.JButton btnRifornisci;
    private javax.swing.JButton btnStatistiche;
    private javax.swing.JButton btnVendi;
    private javax.swing.JComboBox<String> cmbGita;
    private javax.swing.JComboBox<String> cmbStudente;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGestioneMagazzino;
    private javax.swing.JPanel pnlGestioneMagazzino;
    private javax.swing.JPanel pnlTitoloGestioneMagazzino;
    private javax.swing.JTable tableStudenti1;
    // End of variables declaration//GEN-END:variables

}
