/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiugestionegite;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aureli.giulia
 */
public class FrmStudente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStudente.class.getName());
    private DefaultTableModel model;
    /**
     * Creates new form FrmStudente
     */
    public FrmStudente(DefaultTableModel model) {
        initComponents();
        this.model = model;
        configuraComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCreazioneClasse = new javax.swing.JPanel();
        lblCreazioneStudente = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        btnCreaStudente = new javax.swing.JButton();
        cmbClasse = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creazione studente");

        pnlCreazioneClasse.setBackground(new java.awt.Color(153, 204, 255));

        lblCreazioneStudente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreazioneStudente.setText("Creazione studente");

        javax.swing.GroupLayout pnlCreazioneClasseLayout = new javax.swing.GroupLayout(pnlCreazioneClasse);
        pnlCreazioneClasse.setLayout(pnlCreazioneClasseLayout);
        pnlCreazioneClasseLayout.setHorizontalGroup(
            pnlCreazioneClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreazioneClasseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCreazioneStudente)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlCreazioneClasseLayout.setVerticalGroup(
            pnlCreazioneClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreazioneClasseLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblCreazioneStudente)
                .addGap(16, 16, 16))
        );

        lblNome.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblNome.setText("Nome");

        lblCognome.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblCognome.setText("Cognome");

        lblClasse.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblClasse.setText("Classe");

        txtNome.setColumns(5);

        txtCognome.setColumns(5);

        btnCreaStudente.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnCreaStudente.setText("Crea");
        btnCreaStudente.addActionListener(this::btnCreaStudenteActionPerformed);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCognome)
                    .addComponent(lblNome)
                    .addComponent(lblClasse))
                .addGap(25, 25, 25)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbClasse, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreaStudente)
                    .addComponent(txtCognome))
                .addGap(23, 23, 23))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCognome)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasse)
                    .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCreaStudente)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCreazioneClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCreazioneClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreaStudenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaStudenteActionPerformed
        if(controlloTextBox()){
            JOptionPane.showMessageDialog(this, "Inserisci tutti i dati", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nome = txtNome.getText(), cognome = txtCognome.getText();
        Classe classe = (Classe)cmbClasse.getSelectedItem();
        Studente s = new Studente(nome, cognome, classe);
        s.setMatricola(GestioneDatabase.inserisciStudente(nome, cognome, classe.getId()));
        GestioneStudenti.aggiungiStudente(s);
        aggiornaTabella();
    }//GEN-LAST:event_btnCreaStudenteActionPerformed

    /**
     * Metodo per controllare se le text box sono vuote
     * @return true se sono vuote, false altrimenti
     */
    public boolean controlloTextBox(){
        return txtNome.getText().isBlank() || txtCognome.getText().isBlank();
    }
    
    /**
     * Metodo per aggiornare la tabella
     */
    public void aggiornaTabella() {
        model.setRowCount(0);
        for (Studente s : GestioneDatabase.getListaStudenti()) {
            model.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome(), s.getClasse()});
        }
    }

    /**
     * Metodo per inserire btutte le classi sulla combobox
     */
    public void configuraComboBox(){
        for (Classe c : GestioneDatabase.getListaClassi()) {
            cmbClasse.addItem(c);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreaStudente;
    private javax.swing.JComboBox<Classe> cmbClasse;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblCreazioneStudente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlCreazioneClasse;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
