/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinellipichiugestionegite;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martinelli.alessandr
 */
public class FrmVediIscrizioni extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVediIscrizioni.class.getName());
    private Studente s;
    /**
     * Creates new form FrmVediIscrizione
     */
    public FrmVediIscrizioni(Studente s) {
        initComponents();
        this.s = s;
        configuraLabel();
        configuraTabella();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSfondo = new javax.swing.JPanel();
        pnlVediIscrizione = new javax.swing.JPanel();
        lblVediIscrizione = new javax.swing.JLabel();
        lblIscrizioneNome = new javax.swing.JLabel();
        lblIscrizioneCognome = new javax.swing.JLabel();
        lblIscrizioneClasse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVediIscrizioni = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        btnEliminaIscrizione = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vedi iscrizioni");

        pnlVediIscrizione.setBackground(new java.awt.Color(153, 204, 255));

        lblVediIscrizione.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblVediIscrizione.setText("Vedi Iscrizioni");

        javax.swing.GroupLayout pnlVediIscrizioneLayout = new javax.swing.GroupLayout(pnlVediIscrizione);
        pnlVediIscrizione.setLayout(pnlVediIscrizioneLayout);
        pnlVediIscrizioneLayout.setHorizontalGroup(
            pnlVediIscrizioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVediIscrizioneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblVediIscrizione)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        pnlVediIscrizioneLayout.setVerticalGroup(
            pnlVediIscrizioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVediIscrizioneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblVediIscrizione)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblIscrizioneNome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lblIscrizioneNome.setText("Nome:");

        lblIscrizioneCognome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lblIscrizioneCognome.setText("Cognome:");

        lblIscrizioneClasse.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lblIscrizioneClasse.setText("Classe:");

        tblVediIscrizioni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Destinazione", "Durata", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVediIscrizioni);

        btnEliminaIscrizione.setText("Elimina iscrizione");
        btnEliminaIscrizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaIscrizioneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSfondoLayout = new javax.swing.GroupLayout(pnlSfondo);
        pnlSfondo.setLayout(pnlSfondoLayout);
        pnlSfondoLayout.setHorizontalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSfondoLayout.createSequentialGroup()
                .addComponent(pnlVediIscrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSfondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminaIscrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSfondoLayout.createSequentialGroup()
                            .addComponent(lblIscrizioneNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lblIscrizioneCognome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblIscrizioneClasse)
                            .addGap(18, 18, 18)
                            .addComponent(lblClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSfondoLayout.setVerticalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSfondoLayout.createSequentialGroup()
                .addComponent(pnlVediIscrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIscrizioneNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIscrizioneCognome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIscrizioneClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCognome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminaIscrizione)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminaIscrizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaIscrizioneActionPerformed
        int rigaSelezionata = tblVediIscrizioni.getSelectedRow();
        if(rigaSelezionata == -1){
            JOptionPane.showMessageDialog(this, "Seleziona una gita", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Integer idGita = (Integer)tblVediIscrizioni.getValueAt(rigaSelezionata, 0);
        s.rimuoviGita(idGita);
        GestioneDatabase.rimuoviPartecipazione(s.getMatricola(), idGita);
        DefaultTableModel modello = (DefaultTableModel)tblVediIscrizioni.getModel();
        modello.removeRow(rigaSelezionata);
    }//GEN-LAST:event_btnEliminaIscrizioneActionPerformed

    private void configuraLabel(){
        lblNome.setText(s.getNome());
        lblCognome.setText(s.getCognome());
        lblClasse.setText(s.getClasse().toString());
    }
    
    private void configuraTabella(){
        DefaultTableModel modello = (DefaultTableModel)tblVediIscrizioni.getModel();
        for(int id : s.getIdGita()){
            Gita g = GestioneGite.cercaPerId(id);
            modello.addRow(new Object[]{g.getId(), g.getDestinazione(), g.getDurata(), g.getPrezzo()});
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminaIscrizione;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblIscrizioneClasse;
    private javax.swing.JLabel lblIscrizioneCognome;
    private javax.swing.JLabel lblIscrizioneNome;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblVediIscrizione;
    private javax.swing.JPanel pnlSfondo;
    private javax.swing.JPanel pnlVediIscrizione;
    private javax.swing.JTable tblVediIscrizioni;
    // End of variables declaration//GEN-END:variables
}
